export class Resume {
  constructor() {
    this.refs = {
      body: document.querySelector('.js-body'),
      themaBt: document.querySelector('.js-thema'),
      themaImg: document.querySelector('.skills__img'),
      languageTxt: document.querySelector('.language'),
      linkProject: document.querySelectorAll('.info__prodject--link'),
      mapCity: document.querySelector('.adress-city'),
      backdropMap: document.querySelector('.footer__backdrop'),
      enBt: document.querySelector('.js-en'),
      uaBt: document.querySelector('.js-ua'),
      ruBt: document.querySelector('.js-ru'),
      languageModal: document.querySelector('#lang'),
      name: document.querySelector('.js-name'),
      projeckts: document.querySelector('.info__proj'),
      educations: document.querySelector('.info__educations'),
      experience: document.querySelector('.info__experience'),
      aboutMe: document.querySelector('.info__about-me'),
      myEng: document.querySelector('.js-my-eng'),
      myExperience: document.querySelector('.js-my-experience'),
      lastWork: document.querySelector('.js-last-work'),
      selfEducation: document.querySelector('.js-self-education'),
      hobby: document.querySelector('.js-hobby'),
      //   themaBt: document.querySelector('.js-thema'),
      //   themaBt: document.querySelector('.js-thema'),
      //   themaBt: document.querySelector('.js-thema'),
      //   themaBt: document.querySelector('.js-thema'),
      //   themaBt: document.querySelector('.js-thema'),
      //   themaBt: document.querySelector('.js-thema'),
      //   themaBt: document.querySelector('.js-thema'),
      //   themaBt: document.querySelector('.js-thema'),
      //   themaBt: document.querySelector('.js-thema'),
      //   themaBt: document.querySelector('.js-thema'),
    };
  }
}
